# Checkov Configuration File
# Configuration for security and compliance scanning of Terraform code

# Skip checks if needed
# skip-check:
#   - CKV_AWS_46  # Ensure no hard-coded secrets exist in EC2 user data
#   - CKV_AWS_79  # Ensure Instance Metadata Service Version 1 is not enabled

# Framework to scan
framework:
  - terraform

# Directory to scan
directory:
  - .

# Output formats
output:
  - cli
  - junitxml

# Soft fail mode - do not fail the build even if there are issues
soft-fail: false

# Compact output
compact: true

# Download external modules
download-external-modules: true

# Additional checks to run
check:
  - CKV_AWS_79   # IMDSv2 enabled
  - CKV_AWS_8    # Encrypted EBS volumes
  - CKV_AWS_23   # Security groups restrict ingress
  - CKV_AWS_260  # HTTP security headers
  - CKV_AWS_130  # VPC Flow Logs enabled
